version: '3.8'

services:
  relai-backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - N8N_API_KEY=${N8N_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./public:/app/public
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/database-status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
